---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: nginx_centos_8
    image: quay.io/centos/centos:stream8
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: nginx_centos_9
    image: quay.io/centos/centos:stream9
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: nginx_debian
    image: docker.io/debian:stable
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: nginx_ubuntu
    image: docker.io/ubuntu:20.04
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
lint: |
  ansible-lint
  yamllint -c .yamllint .
provisioner:
  name: ansible
  inventory:
    host_vars:
      nginx_debian:
        ansible_python_interpreter: /usr/bin/python3
      nginx_centos_8:
        ansible_python_interpreter: /usr/bin/python3
