---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: ssh {instance}
    ansible_connection_options:
      ansible_connection: ssh
platforms:
  - name: test
provisioner:
  name: ansible
verifier:
  name: ansible
