---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test that nginx redirects to HTTPS
      ansible.builtin.uri:
        url: http://127.0.0.1/
        follow_redirects: none
        status_code: 301

    - name: Test that HTTPS works
      ansible.builtin.uri:
        url: https://127.0.0.1/
        validate_certs: false
        follow_redirects: none
        status_code: 502
